[package]
name = "ccmat-symmetry"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true

[dependencies]
ccmat-core = { path = "../ccmat-core" }

# XXX: symmery hide moyo from other ccmat crate, the ccmat-moyo is temporarily here for experiment
moyo = "0.7.9"
nalgebra = "0.34.1"

